name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install sshpass (required for password authentication)
        run: sudo apt-get install sshpass

      - name: Deploy to Hostinger
        env:
          HOSTINGER_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
        run: |
          sshpass -p "$HOSTINGER_PASSWORD" scp -o StrictHostKeyChecking=no -P 65002 -r public/* u658718463@157.173.209.182:/home/u658718463/domains/soj-i.me/public_html/
